# Generated by Django 2.2 on 2020-12-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=255)),
                ('token_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candlestick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('open_price', models.DecimalField(decimal_places=18, max_digits=38)),
                ('high_price', models.DecimalField(decimal_places=18, max_digits=38)),
                ('low_price', models.DecimalField(decimal_places=18, max_digits=38)),
                ('close_price', models.DecimalField(decimal_places=18, max_digits=38)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=38)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candlesticks', to='prices.Currency')),
            ],
        ),
    ]
