# Generated by Django 2.2 on 2020-12-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_remove_candlestick_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=18, max_digits=38)),
            ],
        ),
    ]
