# Generated by Django 2.2 on 2020-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_auto_20201202_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='block',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
