# Generated by Django 2.2 on 2020-12-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_trade_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='hash',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
