# Generated by Django 2.2 on 2020-12-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlestick',
            name='currency',
        ),
    ]
