# Generated by Django 2.2 on 2020-12-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('timestamp',)},
        ),
    ]
