# Generated by Django 2.2 on 2021-01-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_auto_20201222_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketMaker',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='contract',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='trade',
            name='btc_value',
            field=models.DecimalField(decimal_places=18, default=1, max_digits=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trades.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='eth_value',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='usd_value',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
