# Generated by Django 2.2 on 2021-01-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_auto_20210111_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='currency',
        ),
    ]
