# Generated by Django 2.2 on 2021-01-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_auto_20210112_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='btc_value',
            new_name='btc_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='eth_value',
            new_name='eth_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='usd_value',
            new_name='usd_price',
        ),
    ]
