# Generated by Django 2.2 on 2021-02-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_auto_20210117_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='dea_price',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
            preserve_default=False,
        ),
    ]
